### ISSUE TITLE
Add note that the library is supporting headless only (no templates) to README

### ISSUE THREAD

**Issue by sebastienhasa** [thclark/wagtail_events#20]
Hello.

If I install wagtail-events, create and publish an event page then try to see the live version of this page, I got a `TemplateDoesNotExist` exception.

Wagtail-events version:

0.4.0

**Comment by thclark** [comment]
HI @sebastienhasa - that's intentional.

A lot of wagtail development, including modern torchbox projects, are using wagtail to provide a headless CMS. All mine do, too (like [this one](https://www.traffickingpast.uk/events)), so I don't support templates.

Apologies, I should be clearer about this in the README (I thought this had the same readme as my other projects like wagtail_references).

I would, however, accept a well documented PR with templates if you'd like to contribute one!

**Comment by sebastienhasa** [comment]
Ho, I didn't see that it's a headless app. :) 
As I've seen a templates folder, I was thinking that they were only misnamed.

Yes, I can provide a pull request. See my comment on #19 for more details. ;)
